/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  sara
 * Created: 23-mag-2016
 */

CREATE TABLE saldo
(
    id_saldo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    totale INTEGER
);

CREATE TABLE cliente
(
    id_saldo INTEGER,
    id_cliente INTEGER,
    username VARCHAR(128),
    password VARCHAR(128),
    FOREIGN KEY (id_saldo) REFERENCES cliente (id_cliente)
    
);

CREATE TABLE venditore
(
    id_venditore INTEGER,
    username VARCHAR(128),
    password VARCHAR(128),
    id_saldo INTEGER,
    id_oggetto INTEGER,
    FOREIGN KEY (id_saldo) REFERENCES venditore (id_venditore),
    FOREIGN KEY (id_oggetto) REFERENCES venditore (id_venditore)
);

CREATE TABLE oggetto
(
    id_oggetto INTEGER,
    nome VARCHAR(128),
    url INTEGER,
    prezzo INTEGER,
    quantita INTEGER
);

INSERT INTO saldo (id_saldo, totale)(
VALUES (default, 125),
       (default,55),
       (default,33),
       (default,452),
       (default,186),
       (default,99)
);


INSERT INTO cliente (id_cliente,username, password, id_saldo)
VALUES (20, 'Adele65', 'tfg',default),
       (21, 'Paolo86', 'tfggt', default),
       (22, 'Claudio84', 'tfght', default);

INSERT INTO venditore (id_venditore,username, password, id_saldo)
VALUES (23, 'Sara52', 'abcd',default),
       (24, 'Alessandro86', 'abcde',default),
       (25, 'Vittoria1995', 'abcdef',default);

INSERT INTO oggetto (id_oggetto,nome, url, prezzo, quantita, id_venditore, id_saldo)
VALUES (default, 'Cuscino','img/cuscino.jpg' , 42,2,4 ),
       (default, 'Scatola','img/scatola.jpg', 6,3,5),
       (default, 'Tappeto','img/tappeto.jpg',85,8,6);





